# Generated by Django 5.2.2 on 2025-06-07 06:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('usage_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('key_topics', models.JSONField(default=list, help_text='List of main topics discussed')),
                ('technologies_mentioned', models.JSONField(default=list, help_text='Technologies/languages mentioned')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('token_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Conversation summaries',
            },
        ),
        migrations.CreateModel(
            name='GuardrailsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_query', models.TextField()),
                ('classification_reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('query_category', models.CharField(blank=True, choices=[('general_chat', 'General Conversation'), ('personal', 'Personal Questions'), ('news', 'News/Current Events'), ('math_unrelated', 'Math (Non-Programming)'), ('other', 'Other')], max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_memory_enabled', models.BooleanField(default=True)),
                ('max_memory_messages', models.IntegerField(default=10, help_text='Max messages to remember')),
                ('preferred_agent', models.CharField(blank=True, choices=[('python_agent', 'Python Expert'), ('web_agent', 'Web Development Expert'), ('database_agent', 'Database Expert'), ('algorithm_agent', 'Algorithm Expert'), ('debug_agent', 'Debug Expert'), ('architecture_agent', 'Architecture Expert')], max_length=50)),
                ('prefer_detailed_responses', models.BooleanField(default=True)),
                ('include_examples', models.BooleanField(default=True)),
                ('include_explanations', models.BooleanField(default=True)),
                ('strict_guardrails', models.BooleanField(default=True, help_text='Strict coding-only mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='has_code',
            field=models.BooleanField(default=False, help_text='Whether response contains code'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_guardrails_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response_time_ms',
            field=models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='token_count',
            field=models.IntegerField(blank=True, help_text='Estimated token count', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='User rating for the response', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_agent_used',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='memory_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_context',
            field=models.TextField(blank=True, help_text='Additional session context'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='chatbot_cha_session_488328_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['agent_used'], name='chatbot_cha_agent_u_0e2df4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['-timestamp'], name='chatbot_cha_timesta_c63751_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_guardrails_blocked'], name='chatbot_cha_is_guar_7662cf_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='chatbot_cha_session_9384e5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='chatbot_cha_user_id_52c956_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['-created_at'], name='chatbot_cha_created_c431b1_idx'),
        ),
        migrations.AddIndex(
            model_name='agentusagestats',
            index=models.Index(fields=['agent_name', 'date'], name='chatbot_age_agent_n_a9a3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='agentusagestats',
            index=models.Index(fields=['-date'], name='chatbot_age_date_76831a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentusagestats',
            unique_together={('agent_name', 'date')},
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession'),
        ),
        migrations.AddField(
            model_name='guardrailslog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='guardrailslog',
            index=models.Index(fields=['-timestamp'], name='chatbot_gua_timesta_acf2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='guardrailslog',
            index=models.Index(fields=['query_category'], name='chatbot_gua_query_c_7b88e7_idx'),
        ),
    ]
